language: node_js
node_js: "11"
os:
  - linux
  - osx
  - windows
dist: trusty
sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

addons:
  apt:
    packages:
      - fakeroot
      - rpm

install:
  - npm install

script:
  - npm run lint
  - electron-forge publish
