language: node_js
node_js: "11"
os:
  - linux
  - osx
  - windows
dist: trusty
sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

addons:
  apt:
    packages:
      - fakeroot
      - rpm
  artifacts: 
    region:  "ap-southeast-1"
    working_dir: out

install:
  - npm install
#  - npm update

script:
  - npm run lint
#  - if test -z "$TRAVIS_TAG"; then npm run make; fi
  - electron-forge make
#after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi
